name: CI
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Yarn Workspaces Check
        run: yarn workspaces list --verbose

      - name: Install dependencies
        run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v4

      - name: Test
        run: yarn affected:test --parallel=5

      - name: Build
        run: yarn affected:build --parallel=5
